### ISSUE TITLE
Son inactif dans la vidéo

### ISSUE THREAD

**Issue by mtlde** [betagouv/peps#122]
La vidéo se met en route mais le son n'est pas actif. 
Exemple sur cette XP : https://peps.beta.gouv.fr/#/agriculteur/Guillaume%20Flayol/experimentation/Test%20de%20la%20culture%20du%20Chia%20

**Comment by alemangui** [comment]
C'était un problème de mon coté lors de l'optimisation de la vidéo. J'ai remis la vidéo cette fois-ci avec le son.
