### ISSUE TITLE
Formatage du texte sur le site

### ISSUE THREAD

**Issue by mtlde** [betagouv/peps#126]
### Contexte
Dans Airtable, je peux faire des retours à la ligne, sauter une ligner pour aller plus d'espace ou encore mettre des bullet point. Je ne les retrouve pas sur le site.

### Exemple
Airtable : https://airtable.com/tbl7jwg9D5NhH8LSH/viwLY86h2p5GPdkyU/recoOLBxBUuz1RWau?blocks=hide

![image](https://user-images.githubusercontent.com/20131951/78048336-ddf0bc00-7379-11ea-90d0-389679d1d7ae.png)

Site : https://peps.beta.gouv.fr/#/agriculteur/Thierry%20Desvaux/experimentation/Association%20de%20cultures%20:%20semer%20et%20r%C3%A9colter%20du%20pois%20d'hiver%20avec%20l'orge%20d'hiver

![image](https://user-images.githubusercontent.com/20131951/78048278-c580a180-7379-11ea-8649-e14ffea19f3b.png)

**Comment by alemangui** [comment]
![image](https://user-images.githubusercontent.com/1225929/78052154-ff07db80-737e-11ea-8987-4637ae643ddf.png)
