### ISSUE TITLE
Les liens ne sont plus présents dans les XPs

### ISSUE THREAD

**Issue by mtlde** [betagouv/peps#127]
### Contexte
On ne voit plus les liens qui étaient présents dans Airtable sur les XPs

### Exemple

Airtable : https://airtable.com/tbl7jwg9D5NhH8LSH/viwLY86h2p5GPdkyU/recoOLBxBUuz1RWau?blocks=hide

![image](https://user-images.githubusercontent.com/20131951/78049530-79366100-737b-11ea-8b55-ced891c23107.png)

Site : https://peps.beta.gouv.fr/#/agriculteur/Thierry%20Desvaux/experimentation/Association%20de%20cultures%20:%20semer%20et%20r%C3%A9colter%20du%20pois%20d'hiver%20avec%20l'orge%20d'hiver

![image](https://user-images.githubusercontent.com/20131951/78049687-a125c480-737b-11ea-8793-b22049de389d.png)

**Comment by alemangui** [comment]
Liens à nouveau présents 

![image](https://user-images.githubusercontent.com/1225929/78052321-39717880-737f-11ea-9889-a1856068947c.png)
