### ISSUE TITLE
Ajouter un tracking sur le filtre par catégorie

### ISSUE THREAD

**Issue by mtlde** [betagouv/peps#129]
(Si ce n'est pas déja en place)

### Contexte
Il est intéressant de comprendre comment les agriculteurs utilisent le site, si ils vont plus consulter les profil ou directement les XPs, est ce qu'ils sont intéressés par des problématiques en particulier.. Ca nous aidera a faire évoluer le produit de la meilleur façon possible.

![image](https://user-images.githubusercontent.com/20131951/78158330-625a4200-7441-11ea-9039-c8376e117d31.png)

**Comment by alemangui** [comment]
Des éventements Matomo ont été rajoutés pour l’interaction avec la pagination avec 
le commit bf231cc
