### ISSUE TITLE
Ajouter un tracking sur la pagination des XPs 

### ISSUE THREAD

**Issue by mtlde** [betagouv/peps#130]
(Si ce n'est pas déja en place)

###Contexte
Pareil que https://github.com/betagouv/peps/issues/129 mais avec les pages (car on a dépassé 1 page 🙌 )

![image](https://user-images.githubusercontent.com/20131951/78158624-c977f680-7441-11ea-964a-1fb53b433c51.png)

**Comment by alemangui** [comment]
Des éventements Matomo ont été rajoutés pour la pagination et le filtering avec le commit 
bf231cc
