### ISSUE TITLE
Home : ajouter une XP comme CTA secondaire en bas de page

### ISSUE THREAD

**Issue by mtlde** [betagouv/peps#136]
### Contexte
Sur la page d'accueil une des actions favorisée est le fait de proposer une nouvelle XP. Le bouton est présent dans la navigation et sous forme de texte entre la carte et la liste des XPs.

![image](https://user-images.githubusercontent.com/20131951/78532753-119f6c00-77e8-11ea-9ef9-15832646a35d.png)

### Proposition
Afin de mieux structurer la page (Carte Agri / Liste XP) et de rendre le bouton de proposition d'XP plus accessible :
- ajouter un titre secondaire : https://github.com/betagouv/peps/issues/137
- Proposer une XP > plutôt un bouton CTA secondaire en fin de page

**Comment by alemangui** [comment]
![image](https://user-images.githubusercontent.com/1225929/78536656-7cec3c80-77ee-11ea-842f-4311f2077fd8.png)

**Comment by alemangui** [comment]
![image](https://user-images.githubusercontent.com/1225929/78536753-a311dc80-77ee-11ea-8f44-49f737b0b7c1.png)
