### ISSUE TITLE
Home : Ajouter une section pour la liste d'XPs

### ISSUE THREAD

**Issue by mtlde** [betagouv/peps#137]
### Contexte
Aujourd'hui la carte a un titre "Trouvez des exemples près de chez vous" mais la liste d'XP n'en a pas.

### Proposition
Afin de structurer la page, ajouter une section : Trouver un retour d'expérience (? wording a avalider)

**Comment by alemangui** [comment]
Vu que le titre pour la carte utilise le verbe _Trouvez_ ("Trouve**z** des exemples près de chez vous"), on peut mettre la même conjugaison pour le titre des XP ("Trouve**z** un retour d'expérience") ?

**Comment by alemangui** [comment]
![image](https://user-images.githubusercontent.com/1225929/78536887-d3597b00-77ee-11ea-8ddf-bc422d8de771.png)
