### ISSUE TITLE
Permettre de mettre une description sur les photos et vidéos

### ISSUE THREAD

**Issue by mtlde** [betagouv/peps#141]
### Contexte
Certains agriculteurs prennent des photos de leurs XPs à différents moments (semis, floraison, récolte...). Cela ne ressort pas sur les photos 

### Proposition
Ajouter la possibilité pour l'agriculteur d'ajouter un texte sur sa photos et de l'afficher sur le site

**Comment by alemangui** [comment]
Petite note : ce comportement sera possible dès qu'on n'utilisera plus Airtable, et sera directement disponible/editable dans la console admin.

**Comment by alemangui** [comment]
La migration DB pour ajouter une description pour les photos et vidéos est faite et disponible aujourd'hui dans la page admin. Il reste ajouter ce champ dans le formulaire utilisateur et l'afficher.

**Comment by alemangui** [comment]
Affichage de la description :

![image](https://user-images.githubusercontent.com/1225929/84160425-712b2980-aa6e-11ea-8dbb-ce7389e6b013.png)
![image](https://user-images.githubusercontent.com/1225929/84160517-8f912500-aa6e-11ea-8989-eadebf58c5e7.png)
