### ISSUE TITLE
Permettre d'agrandir les photos et vidéo

### ISSUE THREAD

**Issue by mtlde** [betagouv/peps#142]
### Contexte
On a des vignettes sur le site mais pas de possibilité d'agrandir les photos. Cela pourrait être pertinent pour mieux voir certains détails

### Proposition
Ouvrir en popup un lecteur des photos / vidéo, exemple pour Twitter
![image](https://user-images.githubusercontent.com/20131951/78538455-4e239580-77f1-11ea-92ea-39a3fd9ee64b.png)

**Comment by alemangui** [comment]
Slideshow mode for photos will be implemented based on an overlayed [vuetify's carousel](https://vuetifyjs.com/en/components/carousels/#carousels)

![image](https://user-images.githubusercontent.com/1225929/83945213-7e93aa00-a809-11ea-9d74-974a295db3ca.png)
