### ISSUE TITLE
Modifier le wording du partage d'XP

### ISSUE THREAD

**Issue by mtlde** [betagouv/peps#150]
### Contexte
Le bouton "Proposer une expériemntation" n'est pas vue ou pas bien compris des testeurs. Difficile de savoir exactement pourquoi sans test utilisateurs vidéo / en physique.
Cependant il semble que certains ne trouvent pas clair le wording :

Luc Jacquet : j'ai vu s'identifier en haut [mais après il cherche donc pas évident] et finalement ne trouve pas. Je vois proposer une xp qu'est ce que c'est ça? j'ai l'impression que je vais proposer une xp à une tierce personne.

### Proposition
Changer le wording du bouton (dans la nav et en bas de la home) par "Partager une expérience"

**Comment by alemangui** [comment]
Le commit contient aussi des changements au niveau du wording ailleurs que dans les boutons de partage (e.g., page XP, page agri, header, etc).
