### ISSUE TITLE
Améliorations page de login

### ISSUE THREAD

**Issue by mtlde** [betagouv/peps#169]
Petites améliorations sur cette page :

![image](https://user-images.githubusercontent.com/20131951/84240702-b39c4700-aafe-11ea-8c85-a6534979d6c7.png)

- [x] Mettre le logo en gras comme sur les autres pages du site

- [x] supprimer la phrase " Une fois pour toutes ! Cette identification dure dans le temps, vous n'aurez pas à le faire à chaque fois." pour rendre le texte plus court

- [x] Changer le titre de la page qui s'affiche sur l'onglet, aujourd'hui c'est l'URL de la page on dirait

**Comment by alemangui** [comment]
Mis en preprod :+1:
