### ISSUE TITLE
favoriser la pratique alternance semis de printemps et d'automne

### ISSUE THREAD

**Issue by MaudBlanck** [betagouv/peps#17]
Ajouter un test pour faire nb cultures semis printemps/total cultures de la rotation :
<35% ou >65% faut mettre un gros boost (1,5?) à "favoriser l’alternance de cultures à semis de printemps et d’automne" en gros j’aimerais qu’elle apparaisse quasiment toujours dans ces cas là
ce test est à faire peut importe la problématique demandée par l'utilisateur.

**Comment by MaudBlanck** [comment]
idéalement ce test pourrait être complété par un qui compte le nombre de printemps successifs et de semis d'automne ou fin d'été successifs si >3 boost aussi. du coup si ce test est possible il faudrait partager le boost avec 1.2 pour le pourcentage et 1.2 pour la consécutivité.

**Comment by alemangui** [comment]
Liée à #22

**Comment by alemangui** [comment]
Threshold mis à 75%-25%.
Multiplicateur mis à 2.

**Comment by MaudBlanck** [comment]
yeah vive les tests à venir
