### ISSUE TITLE
Supprimer la page Stats du footer

### ISSUE THREAD

**Issue by mtlde** [betagouv/peps#191]
### Contexte
Cette page stats n'est pas compréhensible pour des utilisateurs non aguerris. Aussi ils ont accès à beaucoup d'info qu'on ne veut pas qu'ils voient forcément (comme les profil d'utilisateurs)

--> Supprimer cette page et ne pas l'indexer sur le sitemap

**Comment by alemangui** [comment]
Mis en preprod :+1:
