### ISSUE TITLE
Série de petites modifications 

### ISSUE THREAD

**Issue by mtlde** [betagouv/peps#211]
- [x] Home, changer le CTA en "J'explore les témoignages"

- [x] Home, déplier par défaut les filtres

- [x] Home, afficher sur desktop 16 XP et non 9

- [x] Compte, par défaut accepter d'être contacté. 

- [x] Compte, changer la phrase "J'accepte d'être contacté par des utilisateurs de Peps qui souhaitent en savoir plus sur mes témoignages"

- [x] Compte, changer la phrase "J'accepte de revoir un email pour me notifier d'un nouveau message envoyé par un utilisateur sur Peps" 

- [x] Compte, modifier le lien dans le bloc aide : https://aide.peps.beta.gouv.fr

- [x] Compte, modifier le wording dans le bloc aide : Vous trouverez tous les articles d'aide, les ressources et les conseils sur le site Peps.

- [x] Ajouter dans le footer un lien vers le centre d'aide 

- [x] Register, mettre la case a cocher avant la phrase pour les CGU

**Comment by alemangui** [comment]
Déployé en preprod :+1:
