### ISSUE TITLE
Compter le nombre d'années dans la rotation entre cultures identiques (appliquer une périodicité acceptable)

### ISSUE THREAD

**Issue by MaudBlanck** [betagouv/peps#22]
Salut, 
j'ai travaillé aujourd'hui sur un cas où la rotation est peu variété et surtout les fourragères reviennent trop souvent. j'ai créé une action mais je ne peux pas mettre les bons éléments de bonus. 
il faudrait que le modèle regarde les cultures présentes dans la rotation concernée par le problème, et qu'il regarde si une culture est présente en laissant moins d'un certain nombre de saisons entre 2 retours.
pour complexifier on pourrait imaginer un mécanisme où les le nombre d'année dépend du problème questionné?

**Comment by alemangui** [comment]
Il y a deux cas :

- **La rotation n'est pas équilibrée par rapport aux saisons de semis**  
Dans ce cas là, il faut privilégier les pratiques qui contribuent à l'équilibre de la rotation.La pratique "Favoriser l'alternance" doit être privilégiée aussi.

- **Compter le nombre d'années dans la rotation entre cultures identiques**
Vue qu'on peut avoir seulement une culture par année, il faut qu'on sache la périodicité acceptable par culture (en années) pour savoir quand il faut allonger la rotation.

**Comment by alemangui** [comment]
Je propose laisser cet issue pour le cas 2 (Compter le nombre d'années dans la rotation entre cultures identiques) et qu'on traite l'équilibre de la rotation dans l'Issue #17

**Comment by alemangui** [comment]
@MaudBlanck Après la conversation d'hier au sujet de l'ordre de la rotation (comme quoi l'ordre ne nous sert pas finalement) est-ce que cet issue reste pertinent ? Si les cultures ne sont pas dans l'ordre nous ne saurons pas le nombre d'années entre cultures, ou même si elles se répètent.

**Comment by MaudBlanck** [comment]
c'est vrai on peut la mettre de côté. on a un test sur le fait que s'il y a peu de cultures ça met un bonus à allonger?

**Comment by MaudBlanck** [comment]
Ya un moyen de faire un récapitulatif de toutes les règles que MIA connait?

**Comment by alemangui** [comment]
@MaudBlanck  oui, on a l'équilibre des cultures déjà mis en place. Cet issue était plutôt pour compter le nombre d'années dans la rotation entre cultures identiques. Pour l'instant je vais le mettre en "Won't fix" mais après on peut revenir si on pense que c'est nécessaire.

Nous n'avons pas documenté les règles que MIA connaît, ce sera bien qu'on le fasse dans le README.md de ce repo. Pour l'instant le code qui les traite est assez lisible : https://github.com/betagouv/peps/blob/master/api/engine.py#L90

Nous avons aussi les tests qui commencent avec des commentaires décrivant les situations ici : https://github.com/betagouv/peps/blob/master/api/tests/test_engine.py

**Comment by MaudBlanck** [comment]
on pourrait faire un truc hyper simple si il y a 3 cultures ou moins dans la rotation citée comme étant celle du système à améliorer on met un bonus de 1.1 à la pratique allongement de la rotation. en fait dans l'idée initiale j'aurais voulu tester des règles de prophylaxie du type pas de pomme de terre plus souvent que tous les 6 ans, idem pour le colza et pas de blé plus que tous les 3 ans. je le note là au cas où on veux repasser du temps un jour là dessus ça peut servir de s'en souvenir.

**Comment by alemangui** [comment]
@MaudBlanck oui on peut faire ça, ça me semble logique, surtout qu'on a déjà l'inverse (si >6 cultures on pénalise les pratiques qui en ajoutent: https://github.com/betagouv/peps/blob/03d9453b01d8929cdac846204880445ec353919c/api/engine.py#L357)
