### ISSUE TITLE
[EMAIL] Le champ titre CTA et le titre de la pratique sont échangés

### ISSUE THREAD

**Issue by mtlde** [betagouv/peps#32]
Dans Cleverapp comme dans la pratique Airtable (https://airtable.com/tblobpdQDxkzcllWo/viwIl6ySkIGCg2zPW/recyMe1cHBaIrm58o?blocks=hide) le CTA est "Voir la pratique en détail"

![image](https://user-images.githubusercontent.com/20131951/66289146-053f6280-e8dc-11e9-92d5-708693fd0d59.png)

Par contre dans le mail je je retrouve pas le meme CTA 
![image](https://user-images.githubusercontent.com/20131951/66289185-2c962f80-e8dc-11e9-855e-26cb534e41db.png)

**Comment by alemangui** [comment]
Bien vu, c'est un bug... ce qui était envoyé c'était le titre du ressource en question. Le fix a été mis en place - maintenant on prend le field CTA Label.
