### ISSUE TITLE
[EMAIL] Formatage des autres documents sur une pratique

### ISSUE THREAD

**Issue by mtlde** [betagouv/peps#33]
Dans le format actuel, la liste des ressources n'est pas très claire et compréhensible
![image](https://user-images.githubusercontent.com/20131951/66310199-de992000-e90b-11e9-92c0-80574a05a996.png)

Je trouve qu'un format en liste est plus lisible, par exemple
![image](https://user-images.githubusercontent.com/20131951/66310136-b6112600-e90b-11e9-9800-034a5c408e26.png)

**Comment by alemangui** [comment]
D'accord avec ça. Est-ce qu'on met "Documents" comme entête de la liste ou plutôt "Resources" ? (ou autre)

**Comment by alemangui** [comment]
Fermé au profit de #77
