### ISSUE TITLE
Pb de la pratique "Faucher les refus de prairie alors qu'il y a eu un gèle des cultures"

### ISSUE THREAD

**Issue by Benjamin-Doberset** [betagouv/peps#45]
retour openlab cote d'or

**Comment by alemangui** [comment]
C'était par rapport au contenu (description, liens, etc)., ou bien par rapport à la pertinence de la pratique suite aux réponses du formulaire ?

**Comment by alemangui** [comment]
Maud tu veux jeter un coup d'oeil à la pratique ?

@Benjamin-Doberset @maudblanck

**Comment by MaudBlanck** [comment]
c'est quoi cette pratique? j'ai faucher les refus de prairie mais rien avec l'histoire du gel des cultures ?!

**Comment by alemangui** [comment]
@Benjamin-Doberset je te l'assigne pour avoir un peu plus d'infos. Si tu penses que ce n'est plus pertinent n'hésites pas à fermer l'issue.

**Comment by alemangui** [comment]
@MaudBlanck pareil, j'ai "Faucher le refus de prairie" mais rien avec le gel. Je ferme celui-ci mais n'hésitez pas a le rouvrir si vous avez plus d'information à ce sujet.
