### ISSUE TITLE
Supprimer la question sur les pratiques essayées

### ISSUE THREAD

**Issue by mtlde** [betagouv/peps#55]
Certaines ne sont pas compréhensibles
Ce n'est pas contextualisé selon les réponses précédentes
C'est très long et favorise le syndrome du "bon élève"

**Comment by alemangui** [comment]
@Maudblanck 

On peut garder seulement les types pour lequels le malus est important pour limiter la taille de cette question sans trop sacrifier son poids dans le calcul. Maud tu es OK pour faire ça depuis la table Airtable? (en enlevant le malus)

**Comment by MaudBlanck** [comment]
il me semble que si on en avait que quelque uns principaux ça serait bien, je n'ai pas d'idée de l'effet bon élève je n'ai pas l'impression qu'ils cochent tout pour le moment ?
si le choix est on teste avec quelques un ou on vire, je vote "on teste avec quelques uns car je crains que la pertinence des réponses s'abaissent si on a plus du tout cette question. en fait c'est une question qui nous différencie d'un moteur de recherche en tenant compte de ce que sait déjà faire l'utilisateur je trouve.

**Comment by alemangui** [comment]
OK dans ce cas là c'est juste une question de modifier la table et rafraichir les données airtable. Je te conseil de dupliquer la colonne pour ne pas perdre les malus originales.

**Comment by mtlde** [comment]
Ils peuvent pas cocher encore donc on a pas testé. Vous avez l'impression que ca apporte un truc vous ? 
En vrai ca ajoute une question et je pense que c'est plus pertinent de les faire dire qu'ils ont déja fait ne pratique une fois affichées

**Comment by MaudBlanck** [comment]
oui je fait ça car on  peut imaginer que si on la  jette en disant "je ne veux pas faire cette pratique car" je fais déjà ça, on réutilise ces malus non?

**Comment by MaudBlanck** [comment]
> 
> 
> Ils peuvent pas cocher encore donc on a pas testé. Vous avez l'impression que ca apporte un truc vous ?
> En vrai ca ajoute une question et je pense que c'est plus pertinent de les faire dire qu'ils ont déja fait ne pratique une fois affichées

ça m'irait comme ça aussi ce serait l'occasion de prendre un feedback sur la pratique (note sur 5 étoiles ou je ne sais quoi qui ressortira des entretiens agriculteurs)

**Comment by MaudBlanck** [comment]
je pense que ça ajoute quand meme en tant qu'humain je m'en servait beaucoup de cette question car comme elle était ouverte ca me permettait de me faire un apriori sur son avancement (le gars qui te site toutes les pratiques existantes versus celui qui te dit glyphosate.
sans doute qu'au niveau automatisation on a pas encore autant tiré parti de cela

**Comment by mtlde** [comment]
Du coup la conclusion c'est : on enlève et on ajoute des actions sur les pratiques ?

**Comment by MaudBlanck** [comment]
ok et on parle du feedback j'ai desjà fait et j'aime bien le 19? je pense que c'est fondamental qu'on puisse creuser cette question et au moins savoir ce qu'on en fait.

**Comment by alemangui** [comment]
OK, du coup on enlève la question et on met le feedback de la suppression dans l'étape d'après

**Comment by mtlde** [comment]
Link #61
