### ISSUE TITLE
[WEB] Ajouter un encart en haut des pages

### ISSUE THREAD

**Issue by mtlde** [betagouv/peps#56]
**Contexte**
Sur les page de questionnaire, avoir 2 encarts :
- un précisant le scope de la solution (grandes culture et polyculture élevage
- un explicitant pourquoi on demande ces infos

**Proposition**
![image](https://user-images.githubusercontent.com/20131951/68684974-aa97c700-0569-11ea-990e-a27b5272f262.png)

**Comment by alemangui** [comment]
L'app Vue JS a désormais l'entête général ainsi qu'un descriptif pour chaque formulaire (images ci-desous)

![image](https://user-images.githubusercontent.com/1225929/70787703-937a0e00-1d8f-11ea-97ed-a6e884249601.png)

![image](https://user-images.githubusercontent.com/1225929/70787741-a1c82a00-1d8f-11ea-9e0b-f08d63ac9710.png)

![image](https://user-images.githubusercontent.com/1225929/70787749-a7257480-1d8f-11ea-988b-98614bd32176.png)
