### ISSUE TITLE
[WEB] Ajouter un encart sur la partie 2 du questionnaire

### ISSUE THREAD

**Issue by mtlde** [betagouv/peps#59]
Comme sur l'encart de la 1ere page on a :
- un premier sur la filière grande culture
- un second pour expliquer pourquoi on pose les questions

Ici le Wording :

Peps est encore en phase de test et a besoin des retours de ses utilisateurs. 
Ces données resteront strictement privées. Nous pourront être amené à vous recontacter si vous en êtes d'accord

**Comment by alemangui** [comment]
_"si vous en êtes d'accord"_ mais du coup on ne les demande pas s'ils sont d'accord ? les réponses à ces questions restent obligatoires non ?

**Comment by mtlde** [comment]
Ouais je sais...  mais en meme temps c'est chelou de leur demander s'il sotn d'accord pour etre reconctactés ici

**Comment by alemangui** [comment]
Ça peut être une question conditionnelle :

1- Peps est encore en phase de test et a besoin des retours de ses utilisateurs. Ces données resteront strictement privées. Nous pourront être amené à vous recontacter si vous en êtes d'accord
- Je suis d'accord
- Je ne suis pas d'accord

Et puis s'ils sont d'accord on montre les questions email/nom/numéro etc

**Comment by mtlde** [comment]
Ouais mais la on risque de ne pas avoir grand monde...
Sinon : 

Peps est encore en phase de test et a besoin des retours de ses utilisateurs.
Ces données resteront strictement privées. Nous pourront être amené à vous recontacter pour connaitre votre satisfaction vis à vis du service

**Comment by mtlde** [comment]
Et dans le questionnaire de satisfaction à la fin on demande si ils sont ok pour etre recontacté ou faire plus de tests..

**Comment by mtlde** [comment]
Lié aux taches #56 et #57

**Comment by mtlde** [comment]
Wording a revoir

**Comment by alemangui** [comment]
@mtlde Suite au dév du https://github.com/betagouv/peps/issues/56 et à l'introduction de la politique de confidentialité, est-ce qu'on garde cet issue ?

**Comment by alemangui** [comment]
Je ferme cet issue suite aux explications ajoutées dans #56. N'hésitez pas à le rouvrir si besoin.
