### ISSUE TITLE
ajouter "utiliser un OAD" dans les pratiques testées

### ISSUE THREAD

**Issue by MaudBlanck** [betagouv/peps#6]
C'est un indicateur d'avancement : en principe ceux qui utilisent un OAD optimisent leur passages de phytos c'est donc un 1er pas dans la réduction. Je ne sais pas comment m'en servir encore mis à part pour mettre de côte les pratiques de ce type là.

**Comment by alemangui** [comment]
Salut Maud. Pour le faire:
- If faut aller dans la table [Types de pratique](https://airtable.com/tblTwpbVXTqbQAYfB/viw3CI0bd8IFbmjAn?blocks=hide)
- puis rajouter une nouvelle ligne avec:
   - **Name :** Le texte visible à l'utilisateur "Utilisation d'un OAD"
   - **Enum code :** OAD
   - **Malus :*** Combien veux-tu qu'on pénalise les pratiques de ce type en cas d'un utilisateur qui sélectionne cette option ? (si tu le laisses en blanc l'option n’apparaîtra pas dans le formulaire)
- Maintenant tu peux aller dans la table [Pratiques](https://airtable.com/tblobpdQDxkzcllWo/viwIl6ySkIGCg2zPW?blocks=hide) et rajouter le nouveau pratice_type OAD aux pratiques pertinentes dans la colonne _Types_.

Une fois que ça soit fait je rajouterai l'enum code dans le backend.

**Comment by alemangui** [comment]
@MaudBlanck je viens de rajouter OAD côté code. Une fois que tu le rajouteras dans Airtable ça marchera tout seul. J'attends ta confirmation pour fermer ce issue.

**Comment by MaudBlanck** [comment]
c'est fait du côté airtable

**Comment by alemangui** [comment]
Nickel, je le vois sur le formulaire :+1: 

![image](https://user-images.githubusercontent.com/1225929/63951934-eb119980-ca7e-11e9-8443-20107b56672e.png)

Du coup je ferme l'Issue
