### ISSUE TITLE
Revoir la liste des cultures 

### ISSUE THREAD

**Issue by mtlde** [betagouv/peps#60]
**Contexte**
Lors de l'openlab on a eu plusieurs retour sur l'aspect non exhaustif de notre liste de cultures, il a été cité par exemple moutarde, sorgho, pois chiche. Mais il y en a bien d'autres

**Proposition**
- [x] Supprimer Vigne
- [ ] Ajout moutarde, sorgho, pois chiche

Dans le même temps, ou plus tard si c'est compliqué, avoir une liste exhaustive prise depuis un document de référence comme cette liste de la PAC (sans tout mettre) : https://www1.telepac.agriculture.gouv.fr/telepac/pdf/tas/2019/Dossier-PAC-2019_notice_cultures-precisions.pdf

Mais du coup un autocomplete serait plus approprié car la liste serait vraiment longue

**Comment by alemangui** [comment]
Pour la vigne, voici un issue lié : https://github.com/betagouv/peps/issues/42

**Comment by alemangui** [comment]
Pour le MVP on fera les deux propositions dans l'issue :+1: 

Pour après, les cultures utilisées sont celles de la table https://airtable.com/tblbHAN04NniLVT5d/viw4vPP8z0awDZaBG?blocks=hide

À terme on peut:
- Rajouter des fallbacks pour les cultures qui ne sont pas traitées de façon spécifique par MIA (e.g., "_autres légumineuses_" pour éviter d'avoir une liste immense
- Catégoriser la culture par type (grandes cultures, arboriculture, etc etc) et rajouter une question au début pour restreindre les choix proposées 

Par rapport à l'autocomplete je trouve qu'une liste cherchable (mix entre autocomplete et liste) serait plus avantageux pour les cultures qui pourraient avoir deux noms ou deux façon de les écrire. Ça combine la discoverabilité des choix ainsi que la rapidité pour les chercher.

**Comment by alemangui** [comment]
@MaudBlanck Pour le deuxième item (_ajout moutarde, sorgho, pois chiche_) je te laisse le mettre sur la table des cultures ? (Il n'y a pas de changement dans le code à faire pour ajouter ces cultures).

**Comment by alemangui** [comment]
@Maudblanck fais-nous signe quand ces cultures seront ajoutées pour fermer cet issue

**Comment by alemangui** [comment]
@MaudBlanck a ajouté les cultures, je ferme celui-ci
