### ISSUE TITLE
[WEB & APP] Retours sur la pop up "Essayer cette pratique"

### ISSUE THREAD

**Issue by mtlde** [betagouv/peps#62]
**Contexte**
Dans la version actuelle de l'app et de la webapp, derrière le bouton "Essayer cette pratique", on demande à l'agriculteur les points sur lesquels il veut solliciter l'équipe.
C'est le même comportement qu'avec le test du prototype en mode concierge. Aujourd'hui, on arrive pas à répondre aux personnes qui nous ont sollicité sur des sujets (ils sont encore dans la case "mise en place" sur Asana)

Par contre, on a une liste de freins identifiés à la mise en place des pratiques. On a aussi des pistes de solutions qu'on souhaite creuser dans les 6 prochains mois.

**Proposition**
Je pense que c'est le bon endroit pour tester nos différents freins et pistes de travail + récupérer des testeurs qualifiés pour mener des entretiens plus poussés. Du coup dans cette partie, je changerais d'approche.

- Bouton : `En savoir plus` ou `Cette pratique m'intéresse` par exemple

- Message de la page / pop up suivante : 

Cette pratique vous intéresse ?
Quelles informations ou actions vous semblent nécessaires afin de vous décider sur le test de cette pratique (il est possible de sélectionner plusieurs items) : 
- échanger avec mon conseiller
- avoir le retour d'expérience d'un agriculteur l'ayant déjà mis en place
- obtenir plus de documentation technique et un protocole de test
- connaitre les aides disponibles pour cette pratique
- connaitre les cahiers des charges incluant cette pratique
- avoir une estimation du risque économique pris 
- chercher les débouchés disponibles pour cette nouvelle culture (si pertinent)
- connaitre le matériel nécessaire et disponible (si pertinent)
- autre, précisez

Acceptez-vous d'être recontacté lors de notre travail sur ces différents sujets ?

Par exemple ça peut donner quelque chose comme ça - sauf la dernière partie : 

![image](https://user-images.githubusercontent.com/20131951/68695650-b8eede80-057b-11ea-9663-7a78767b4c36.png)

A discuter entre nous

**Comment by alemangui** [comment]
J'aurai besoin d'en discuter un peu plus à ce sujet - surtout lié à l'action derrière

**Comment by alemangui** [comment]
Compléter automatiquement les données de contact avec ce qu'ils ont mis dans le formulaire.
