### ISSUE TITLE
[APP] Boutons < et > non accessibles

### ISSUE THREAD

**Issue by mtlde** [betagouv/peps#63]
Quand la liste d'item est longue, on ne voit pas les boutons

Il faut trouver des inspirations UI pour la réalisation

**Comment by alemangui** [comment]
Duplicate de : https://github.com/betagouv/peps-app/issues/13

**Comment by alemangui** [comment]
Si ça vous va je fermerai celui-ci au profit du https://github.com/betagouv/peps-app/issues/13
