### ISSUE TITLE
[APP] Ajout de la mention du scope grandes cultures 

### ISSUE THREAD

**Issue by mtlde** [betagouv/peps#65]
**Contexte**
L'utilisateur qui arrive sur l'app ne sait pas que les pratiques ne sont disponibles que pour les systèmes en grandes cultures et polyculture élevage. 

**Proposition**
Au niveau de la page d'accueil, j'ajouterais la mention que le service est uniquement disponible pour les systèmes grandes culture et polyculture élevage (comme sur le web)

Voir l'adaptation de la page ensemble

**Comment by alemangui** [comment]
@maudblanck je pense que ça serait très utile en effet de l'avoir pour MVP, même si ce n'est qu'un petit mot en haut genre: 

![image](https://user-images.githubusercontent.com/1225929/68848607-e0a38b00-06d0-11ea-9e0b-c85355806db3.png)

**Comment by MaudBlanck** [comment]
je pense que ça pourra être bien d'en parler le 19 car c'est le genre d'annonce qui peut permettre de faire que l'utilisateur se sent plus investi "Faites le tri dans les pratiques disponibles pour sélectionner celles qui vous intéresses et aidez à enrichir le contenu de celles que vous avez déjà testé "

**Comment by alemangui** [comment]
![image](https://user-images.githubusercontent.com/1225929/70715429-90791200-1cea-11ea-87ad-02272352c221.png)

Disponible en preprod
