### ISSUE TITLE
[APP & WEB] Ajout d'un bouton pour recommencer la simulation

### ISSUE THREAD

**Issue by mtlde** [betagouv/peps#66]
**Contexte**
Quand on est sur la page de pratiques on est un peu coincés si on veut refaire une simulation ou revenir à l'écran d'accueil
Sur l'app il faut appuyer 15 fois sur la flèche de haut à gauche
Sur la web app  il faut faire un retour navigateur ou bien changer l'RL

**Proposition**
En bas des 3 pratiques, avoir un bouton "Recommencer la simulation" ou "Revenir à l'accueil" 

Voir comment on peut l'intégrer dans la page pour que ça ne devienne pas un CTA

**Comment by alemangui** [comment]
![image](https://user-images.githubusercontent.com/1225929/70714965-860a4880-1ce9-11ea-947b-ad136d2a5734.png)
Ajout du link "Revenir au formulaire" dans le cadre explicatif des suggestions dans un premier temps. N'hésites pas à re-ouvrir si besoin de faire une implémentation UI différente.

**Comment by alemangui** [comment]
Je ferme cet issue vu qu'on mettra en place les breadcrumbs (en plus du fix déjà fait)
