### ISSUE TITLE
[WEB & APP] Labeliser les pratiques

### ISSUE THREAD

**Issue by mtlde** [betagouv/peps#67]
**Contexte**
On a eu plusieurs retours de testeurs qui ne comprennent pas l'ordre des pratiques ni notre volonté d'avoir des pratiques de difficultés différentes.

**Proposition**
Dans la base Airtable, plusieurs indicateurs pourraient être intéressant à faire apparaitre, de façon brut ou retravaillé :
- précision
- difficulté
- type ESR

**Comment by alemangui** [comment]
@mtlde Suite aux dernières discussions on garde cet issue ouvert ?

**Comment by alemangui** [comment]
En vue des expériences UI qu'on mène en ce moment, cet issue n'est plus d'actualité
