### ISSUE TITLE
[WEB] La version webapp mobile n'est pas utilisable 

### ISSUE THREAD

**Issue by mtlde** [betagouv/peps#68]
**Contexte**
La webapp n'est pas lisible sur mobile
![image](https://user-images.githubusercontent.com/20131951/68750113-aae2a180-05ff-11ea-8f20-7586a16f538b.png)
Ecran galaxy S5

**Proposition**
Soit ajouter un bandeau natif pour rediriger vers l'app
Soit avoir une version mobile semblable a celle de l'app
Soit avoir une vraie webapp responsive

**Comment by alemangui** [comment]
On pourra mettre les bandeau pour télécharger l'appli web dès que l'appli soit dans le store. Cela me semble plus raisonnable pour ne pas maintenir deux versions mobiles.

**Comment by alemangui** [comment]
![image](https://user-images.githubusercontent.com/1225929/70715086-d681a600-1ce9-11ea-9d15-275b675a7188.png)
Reglé avec la version Vue JS.
