### ISSUE TITLE
[WEB & APP] Homogénéiser les expériences

### ISSUE THREAD

**Issue by mtlde** [betagouv/peps#69]
A plusieurs endroits, on a pas la même expérience sur la webapp et sur l'app :

- [ ] La marge de manoeuvre est explicité dans l'app et pas dans la web app
- [ ] Les boutons sur les pratiques ne sont pas les mêmes, les pictos en particulier
- [ ] l'UI des pratiques (couleur, typo, taille de police...) ne sont pas les mêmes 
- [ ] Les pages / pop up "essayer cette pratique" et "recalculer sans cette pratique" sont différentes (UI et wording)
- [ ] ...

On peut se faire une passe sur les différents éléments

**Comment by alemangui** [comment]
Suite à la fin de support de l'app, je vais fermer cet issue
