### ISSUE TITLE
[APP & WEBAPP] Sélection multiple intérêt pour la pratique  

### ISSUE THREAD

**Issue by mtlde** [betagouv/peps#73]
L'utilisateur peut sélectionner plusieurs items car il a potentiellement besoin de plusieurs infos avant la mise en place de la pratique

![image](https://user-images.githubusercontent.com/20131951/69408002-28946480-0d06-11ea-9283-f0227cd18076.png)

**Comment by alemangui** [comment]
![image](https://user-images.githubusercontent.com/1225929/70715177-04ff8100-1cea-11ea-9ea4-c21ced40bd31.png)

Reglé avec la version Vue JS
