### ISSUE TITLE
adapter la pertinence à l'adventice

### ISSUE THREAD

**Issue by MaudBlanck** [betagouv/peps#8]
Je suis en train de regarder les pratiques contre les adventices vivaces et il est évident du fait de la biologie des différentes plantes que des pratiques sont favorisantes pour certaines adventices. pourrait-on envisager que dans le cas où l'utilisateur dit j'ai un problème de chardon, la pratique labour et luzerne qui sont des leviers partiels très efficaces soient bonifiés. de même pour liserons et les autres adventices?

**Comment by alemangui** [comment]
Ce serait donc un modèle comme pour les departements, dans lequel on a la possibilité de mettre un place un bonus par combinaison _pratique-adventice_ ou _pratique-ravageur_ ?

**Comment by MaudBlanck** [comment]
oui je pense il faudrait le faire pour implanter une culture fouragère fauchée et chardon, culture fourragère fauchée et liseron,

**Comment by alemangui** [comment]
@MaudBlanck la table [Pratiques/Adventices](https://airtable.com/tbl0RJ5WcrI0SsxvZ/viwyiVsLzx9kYUj5x?blocks=hide) a été crée sur Airtable, tu peux l'utiliser dans la colonne du même nom dans la table _Pratiques_. Je vais maintenant faire le lien côté backend pour prendre en compte ce nouveau field.

**Comment by alemangui** [comment]
@MaudBlanck 
Ceci soulève la question du rôle du whitelist vs multiplicateur.

On aura donc des colonnes whitelist pour adventices, ravageurs et cultures, ainsi que des colonnes multiplicateurs pour les trois.

Les whitelist seront rarement utilisés. Il n'y aurait que les pratiques très précises qui en auront besoin (_e.g._, "Profiter de l'action des auxiliaires sur le puceron de l'épi" sera whitelisté pour le puceron, pas de raison de proposer ça pour d'autre ravageurs).
